name: Master

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-cache-
      - name: Cache Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper-
      - name: Cache Android Gradle Plugin
        uses: actions/cache@v1
        with:
          path: ~/.android/build-cache
          key: ${{ runner.os }}-android-gradle-cache-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-android-gradle-cache-

      - name: Run unit tests
        run: ./gradlew testDebug --stacktrace

  apk:
    name: Generate Bundle
    needs: test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Decrypt secrets folder
        run: ./.github/scripts/decrypt_secrets.sh
        env:
          SECRETS_GPG_PASSPHRASE: ${{ secrets.SECRETS_GPG_PASSPHRASE }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-cache-
      - name: Cache Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper-
      - name: Cache Android Gradle Plugin
        uses: actions/cache@v1
        with:
          path: ~/.android/build-cache
          key: ${{ runner.os }}-android-gradle-cache-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-android-gradle-cache-

      - name: Build Release Bundle
        run: ./gradlew bundleRelease --stacktrace

      - name: Upload Bundle
        uses: actions/upload-artifact@v1
        with:
          name: go-dentist
          path: app/build/outputs/bundle/release/app-release.aab
