name: Feature branch

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-cache-
      - name: Cache Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper-
      - name: Cache Android Gradle Plugin
        uses: actions/cache@v1
        with:
          path: ~/.android/build-cache
          key: ${{ runner.os }}-android-gradle-cache-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-android-gradle-cache-

      - name: Run unit tests
        run: ./gradlew testDebug --stacktrace
